using Microsoft.CodeAnalysis;

namespace SourceGen
{
    [Generator(LanguageNames.CSharp)]
    public sealed class HelloWorldGenerator : ISourceGenerator
    {
        void ISourceGenerator.Execute(GeneratorExecutionContext context)
        {
            const string version = "1.0";
            context.AddSource("TestFile.cs",
                $$"""
                //<auto-generated/>
                #nullable enable

                namespace GenCode
                {
                    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(HelloWorldGenerator)}}","{{version}}")]
                    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                    public static class GeneraredClass
                    {
                        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("{{nameof(HelloWorldGenerator)}}","{{version}}")]
                        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
                        public static void Hello()
                        {
                            global::System.Console.WriteLine("代码生成成功");
                        }
                    }
                }
                """
                );
        }

        //初始化，筛选条件
        void ISourceGenerator.Initialize(GeneratorInitializationContext context)
        {
            
        }
    }
}
